on: push
name: npm build, lint, test and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: npm install
        uses: actions/npm@main
        with:
          args: install
      - name: docker build
        uses: actions/docker/cli@main
        with:
          args: build -t ugoslim/nodebackend ./server .
      - name: docker login
        uses: actions/docker/login@main
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: docker push
        uses: actions/docker/cli@master
        with:
          args: push ugoslim/nodebackend
